# Generated by Django 5.1 on 2024-08-14 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_userpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('can_create', models.BooleanField(default=False)),
                ('can_read', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.user')),
            ],
        ),
        migrations.DeleteModel(
            name='UserPermission',
        ),
    ]
