# Generated by Django 5.1 on 2024-08-14 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_role_userrole_delete_userpermission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='role',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_create',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_read',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_update',
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create', models.BooleanField(default=False)),
                ('can_read', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.user')),
            ],
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
