# Generated by Django 5.1 on 2024-08-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_rename_role_role_name_remove_role_can_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
