# Generated by Django 5.1 on 2024-08-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_alter_userpermission_role_delete_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('date', models.DateField()),
                ('age', models.IntegerField(max_length=4)),
            ],
        ),
    ]
